---
- hosts: "{{ test_hosts|default('all') }}"
  become: yes
  become_method: sudo
  vars_files:
    - 'defaults/main.yml'
  vars:
    ## Java 主版本 
    java_version: 8
    ## java 子版本
    java_subversion: 112
    java_download_path: /tmp
    java_download_from_oracle: true
    #jdk_tarball_file: jdk-8u73-linux-x64
    java_remove_download: true
    java_set_javahome: true
    java_default_link_name: default
    java_home: /usr/java/default
    java_install_dir:  /usr/local/java

  tasks:
    - include: 'tasks/main.yml'

